In [67]:
import torch

In [68]:
X = torch.tensor([[1.0, 4.0, 7.0], [2.0, 3.0, 6.0]])

In [69]:
X

tensor([[1., 4., 7.],
        [2., 3., 6.]])

In [70]:
X.shape

torch.Size([2, 3])

In [71]:
X.dtype

torch.float32

In [72]:
X[0, 1]

tensor(4.)

In [73]:
X[:, 1]

tensor([4., 3.])

In [74]:
X.max(dim=0)

torch.return_types.max(
values=tensor([2., 4., 7.]),
indices=tensor([1, 0, 0]))

In [75]:
X.T

tensor([[1., 2.],
        [4., 3.],
        [7., 6.]])

In [76]:
X @ X.T

tensor([[66., 56.],
        [56., 49.]])

In [77]:
X[:,1] = -99
X.relu_()

tensor([[1., 0., 7.],
        [2., 0., 6.]])

In [78]:
if torch.backends.mps.is_available():
    device = 'mps'
else:
    device = 'cpu'

In [79]:
device

'mps'

In [80]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]]) # create tensor on cpu
M = M.to(device)

In [81]:
M.device

device(type='mps', index=0)

In [82]:
M = torch.tensor([[1., 2., 3.], [4., 5., 6.]], device=device) # create tensor on gpu

In [83]:
R = M @ M.T
R

tensor([[14., 32.],
        [32., 77.]], device='mps:0')

In [84]:
M = torch.rand((1000, 1000))
%timeit M @ M.T

1.03 ms ± 103 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [85]:
M = torch.rand((1000, 1000), device='mps')
%timeit M @ M.T

585 μs ± 3.25 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [86]:
M = torch.rand((4000, 4000), device="mps")

def matmul():
    M @ M.T
    torch.mps.synchronize()  # wait for the GPU to actually finish

%timeit matmul()

36.4 ms ± 1.14 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [87]:
M_cpu = torch.rand((4000, 4000))
%timeit M_cpu @ M_cpu.T

75.2 ms ± 10 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [88]:
x = torch.tensor(5.0, requires_grad=True)
y = 3 * x + 1
f = y ** 2
f

tensor(256., grad_fn=<PowBackward0>)

In [89]:
f.backward()
x.grad

tensor(96.)

In [90]:
x = torch.tensor(5.0, requires_grad=True)
(x ** 2).backward()
(x ** 2).backward()
x.grad

tensor(20.)

In [91]:
x = torch.tensor(5.0, requires_grad=True)
f = x ** 2
f.backward()
x.grad

tensor(10.)

In [92]:
learning_rate = 0.1

with torch.no_grad():
    x -= learning_rate * x.grad

In [93]:
x

tensor(4., requires_grad=True)

In [94]:
x_detached = x.detach()
x_detached -= learning_rate * x.grad

In [95]:
x_detached

tensor(3.)

In [96]:
x.grad.zero_()

tensor(0.)

In [ ]:
learning_rate = 0.1
x = torch.tensor(5.0, requires_grad=True)
for iterator in range(100):
    f = x ** 2 # forward pass
    f.backward() # backward pass
    with torch.no_grad(): # tells pytorch not to record this operation 
        x -= learning_rate * x.grad # gradient descent step

    x.grad.zero_() # reset the gradients for the new pass

In [98]:
x

tensor(1.0185e-09, requires_grad=True)